swagger: "2.0"
info:
  version: 1.0.0
  title: lawyer's Hub
  description: find lawyers.
  termsOfService: no terms.
  contact:
    name: Mudit Kaushik
    url: https://www.linkedin.com/in/mudit-kaushik-62939a3a
    email: mudit.mohan@powerschool.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

host: localhost:1802
basePath: /api
schemes:
    - http
paths:
  /common/country:
    get:
      summary: common data.
      description: common data.
      tags:
        - Common API
      produces:
        - application/json
      responses:
        200:
          description: OK
  /common/states:
    get:
      summary: country states
      description: return country's states
      tags:
        - Common API
      responses:
        200:
          description: OK
  /common/city/{name}:
    get:
      summary: return cities for given states.
      description: return cities for given states.
      tags:
        - Common API
      parameters:
        - in: path
          name: name
          type: string
          required: true
          description: State name must be in string format.
      responses:
        200:
          description: OK
        400:
          description: Bad Request.
    
    
    
