swagger: "2.0"
info:
  version: 1.0.0
  title: lawyer's Hub
  description: find lawyers.
  termsOfService: no terms.
  contact:
    name: Mudit Kaushik
    url: https://www.linkedin.com/in/mudit-kaushik-62939a3a
    email: mudit.mohan@powerschool.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT

host: localhost:1802
basePath: /api
schemes:
    - http
securityDefinitions:
  Authorization:
    type: apiKey
    in: header
    name: bearer token

parameters:
  userid:
    in: query
    name: userid
    required: true
    type: string
    description: logged in userid.

paths:
  /common/country:
    get:
      summary: common data.
      description: common data.
      tags:
        - Common API
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/response"
  /common/states:
    get:
      summary: country states
      description: return country's states
      tags:
        - Common API
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/response"
  /common/city/{name}:
    get:
      summary: return cities for given states.
      description: return cities for given states.
      tags:
        - Common API
      parameters:
        - in: path
          name: name
          type: string
          required: true
          description: State name must be in string format.
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/response"
        400:
          description: Bad Request.
          
  /individual/login:
    post:
      summary: returns token.
      description: returns token with identity.
      tags:
        - Individual API
      parameters:
        - in: body
          name: login
          description: get user credentions.
          schema:
            $ref: '#/definitions/login'
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/response"
  /individual/adduser:
    post:
      summary: register user.
      description: register individual to application.
      tags:
        - Individual API
      parameters:
        - in: body
          name: user
          description: get individual information to create account.
          schema:
            $ref: "#/definitions/register"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/response"
  
  /client/add/{userid}:
    post:
      summary: add client.
      description: add client to the registered user directory.
      tags:
        - Client API
      parameters:
        - $ref: "#/parameters/userid"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/response"

definitions:
  response:
    type: object
    properties:
      success:
        type: boolean
      result:
        type: object
      error:
        type: string
  login:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
  register:
    type: object
    required:
      - firstName
      - lastName
      - email
      - phone
      - username
      - password
    properties:
      firstName:
        type: string
      middlename:
        type: string
      lastName:
        type: string
      email:
        type: string
      phone:
        type: string
      username:
        type: string
      password:
        type: string
  client:
    type: object
    required:
      - userid
      - firstName
      - lastName
      - address1
      - country
      - state
      - district
      - city
      - pincode
      - email
      - phone
      - purpose
      - isprivate
    properties:
      userid:
        type: string
      firstName:
        type: string
      middleName:
        type: string
      lastName:
        type: string
      address1:
        type: string
      address2:
        type: string
      country:
        type: string
      state:
        type: string
      district:
        type: string
      city:
        type: string
      pincode:
        type: string
      email:
        type: string
      phone:
        type: string
      purpose:
        type: number
      occupation:
        type: string
      about:
        type: string
      isprivate:
        type: boolean